### ISSUE TITLE
Engines Attached After Launch Consume Fuel But Provide No Thrust

### ISSUE THREAD

**Issue by JonathanStern** [KospY/KAS#153]
EDIT: 
Problem: KSP Kerbal Space Program Engine Not Providing Thrust
Solution: Make sure nothing is "behind" the engine which might obstruct its thrust. In my example below, the solar panels "blocked" the thrust despite being several meters away.

I radially attached two Thud engines after launching my munar outpost to help deorbit and land the thing. Once activated, the engines do throttle up and consume fuel but provide no thrust.

Relevant are KIS + KAS, MechJeb and Alarm Clock. I have OPT as well for spaceplane parts, none of which were used on this ship.

Could not upload a save to illustrate the issue, but it seems I'm not the first to encounter it. Any help or workarounds would be appreciated!

KIS v1.2.2.0
KAS v0.5.4.0
KSP v1.0.4

**Comment by TechToolbox** [comment]
Hi there. I have experienced this problem before. It was not due to any of the aforementioned  mods I think but due to part placement. If the thrust output of you engine is blocked by another parts collision mesh it does not work or if partially blocked only provides partial thrust output for 5he same fuel. Try moving the engines around or mounting them on pylons or struts to lift them clear of the main craft. Pictures in Dropbox or Google Drive would help with diagnosis I think.

**Comment by TechToolbox** [comment]
P.S. By pics I mean a screenshot.

**Comment by JonathanStern** [comment]
Thanks for the response, here are a couple screengrabs:
http://imgur.com/a/OyWfd

The radial engines were packed into the KIS container and then attached in-flight.

**Comment by JonathanStern** [comment]
Thanks for the good tip -- I tried the obvious (moved them to not be aligned with the solar panels) and it fixed the issue. KIS + KAS was falsely accused! MUCH APPRECIATED!
