### ISSUE TITLE
[1.0.5] Time warp breaks connections.

### ISSUE THREAD

**Issue by KAmaia** [KospY/KAS#163]
I haven't figured out *exactly* what is causing this yet, but in 1.0.5 using the latest version of KAS if I leave my base and switch to a ship in orbit, and then time warp, the connectors on my base un-attach themselves from the ground connector.  I have not tried this with the pylon yet, and that seems to be the only part that causes the issue, as the other end of the link is just fine.

**Comment by ihsoft** [comment]
Current version of KAS is for 1.1. Do you see the same problem on 1.1? There were changes in the pylon config.

**Comment by KAmaia** [comment]
I am still waiting for my mods to update to 1.1, so I cannot test if KAS
exhibits the same behaviour there.

**Comment by labo-css** [comment]
On 1.1.2 i have a big wobble everytime i load my minmus base, everything finally break apart... Is this issue recurrent? How to avoid it?

**Comment by ihsoft** [comment]
Physics artefacts in time warp is a known issue of KSP. KAS and KIS just make this issue worse because people start constructing big bases where stress accumulates faster. I haven't found a way to prevent base breakage when first loading of 1.0.5 save game in 1.1+. Though, if base components survived the impact you may reattach the components and it will be fine after that )more or less).

Another great problem is landing legs. Squad did two major attempts already to fix them but they still behaves odd. So, if your base has landing legs you're in torubles.

As a workaround I'd recommend the following:

1. Loading the base in cheat mode.
2. Detach all KAS connections.
3. On modules with landing legs do retract/extend. Note that module may jump into the sky - it's a KSP issue, not resolved till now.
3. Disable cheat mode and re-connect the components. If you can try to reconstruct the base without landing legs extended. They make physics really weird.

**Comment by labo-css** [comment]
Cheat mode? You mean alt-f12? How can i detach in cheat mode, even with some options ticked the base fall apart in 10s.

Also, is it less risky to build orbital?

**Comment by ihsoft** [comment]
Let me check the game when I'm at home. I remember cheat mode (alt+f12) allows tweaking the physics.

Building on orbit is much less risky. The main problem on surface is interaction of parts and the surface collider. When base is small it's not a big deal but when there are many contact points it may result in a very strange behavior.

**Comment by labo-css** [comment]
No results so far, the base continue to go nuts almost every time i load it

**Comment by ihsoft** [comment]
Hey,

I figured out a "solution" that may work. In KAS part `cPort1` manually edit config part, and change all values of `breakForce` to `1`. Then load the save file with your base. It's expected that every single connection will break but due to the small force the impact to the other modules should be little or none. If it worked then save the state with broken base, restore values in the config, reload the game and restore the base. Connections made on 1.1 will either explode immediately or will work fine :)

**Comment by ihsoft** [comment]
I assume this issue is either resolved or no more relevant.
