### ISSUE TITLE
Fuel transfer doesn't work in 1.2

### ISSUE THREAD

**Issue by poma** [KospY/KAS#189]
I've tried to link 2 vessels with a pipe and fuel transfer doesn't work http://imgur.com/a/cnRMK. I've already seen [a few more threads](https://www.reddit.com/r/KerbalSpaceProgram/comments/58pg1h/kaskis_question_about_fuel_transfer/) with the same issue. Attaching with a winch doesn't help.

This problem happens only when "Resource Transfer Obeys Fuel Crossfeed" is turned on in difficulty settings.

Transfer works for all other resources except fuel. It also starts to work in rare cases when I first dock vessels with a winch and then add a pipe (but it doesn't always work).

I have KSP 1.2, KAS 0.6, KIS 1.3

**Comment by ihsoft** [comment]
Old KAS creates links without using attach nodes. Without it parts are considered disconnected in terms of transferring fuel. This will not be fixed in old KAS but it's already addressed in KAS 1.0 Beta. As for now TJ-1 or TJ-2 allow transferring fuel but this is only for the beta stage, in the future there will be a special part to pump fuel.

**Comment by poma** [comment]
So there is no way to transfer fuel using winches and pipes in KAS 0.6, correct?

**Comment by ihsoft** [comment]
Correct. In the strict mode KSP 1.2 won't let fuel flowing.
